### ISSUE TITLE
CoreMLTools Latency Discrepancy

### ISSUE THREAD

**Issue by ATPAustinPeng** [snap-research/MobileR2L#10]
Hello! I'm trying to reproduce your work and apply compression techniques for one of my courses at Georgia Tech. Do you have results for latency on iPhone 15 or iOS 17?

So far, all my results have been good except for latency. When rendering the model with CoreMLTools using their performance tab, I'm getting around 170 ms latency.

Do you know why this might happen if you don't have results for my configuration? I've attached the mlpackage if you want to try it for yourself.

[lego.mlpackage.zip](https://github.com/snap-research/MobileR2L/files/15214551/lego.mlpackage.zip)

**Comment by galalalala** [comment]
Hi, your mlpackage doesn't seem correct. I attached mine here for reference.
[Relu__Lego_6rb__800_MipNeRF_Fine_LR_D1.onnx.zip](https://github.com/snap-research/MobileR2L/files/15224067/Relu__Lego_6rb__800_MipNeRF_Fine_LR_D1.onnx.zip)
