### ISSUE TITLE
how to support real-world unbound 360 scenes?

### ISSUE THREAD

**Issue by zhouilu** [snap-research/MobileR2L#3]
no space contraction techniques were employed in ngp. but if we use other teathers (like mip-nerf360),  will it work?

**Comment by galalalala** [comment]
Yes. In the orginal paper we used `MipNeRF` and `NeRF` as the teachers but the data distillation took quite a long time. So any teacher will work if the coordinate systems are aligned with the student. For real-world data and my own observations, `ngp_pl` worked well if the scene is not too deep.
