### ISSUE TITLE
iOS / Android SDK?

### ISSUE THREAD

**Issue by legel** [snap-research/MobileR2L#6]
This is great work, which solves so many core problems outside of those directly of concern to Snap.

Is there any chance there is a lower-level iOS / Android codebase for neural rendering in a similar fashion (as was necessary to solve here, in some sense) which you guys used or developed, which you could point me to?

**Comment by galalalala** [comment]
Hi, our work was built upon Snap's public tool [SnapML](https://docs.snap.com/lens-studio/references/guides/lens-features/machine-learning/ml-overview) in which all low-level implementations are encapsulated. You can follow this [tutorial](https://github.com/Snapchat/snapml-templates/tree/main/Neural%20Rendering) on how to run the model on SnapML.

Thanks!
