### ISSUE TITLE
Ask some questions

### ISSUE THREAD

**Issue by Wangman1** [snap-research/MobileR2L#7]
Hi, thank you for your perfect work. I have great interest in studying it. I would like to ask that my own nerf project uses torch_ngp related tools (gridencoder, raymarching, etc.). If I want to apply your method to my own nerf project, What key modules do I need to replace

**Comment by galalalala** [comment]
Hi, you need to distill the data as usual(be careful about the camera conventions) and add super-solution modules to your own work. Then follow the training pipeline to train your own model.
